export const supportedAssets = [
  // { symbol: "MATIC", address: "0xMATIC" },
  { symbol: "WMATIC", address: import.meta.env.VITE_WMATIC },
  { symbol: "WBTC", address: import.meta.env.VITE_WBTC },
  { symbol: "WETH", address: import.meta.env.VITE_WETH },
  { symbol: "AVAX", address: import.meta.env.VITE_AVAX },
  { symbol: "AAVE", address: import.meta.env.VITE_AAVE },
  { symbol: "BNB", address: import.meta.env.VITE_BNB },
  { symbol: "COMP", address: import.meta.env.VITE_COMP },
  { symbol: "GRT", address: import.meta.env.VITE_GRT },
  { symbol: "LINK", address: import.meta.env.VITE_LINK },
  { symbol: "MKR", address: import.meta.env.VITE_MKR },
  { symbol: "Aave market AAVE ", address: import.meta.env.VITE_amAAVE },
  { symbol: "Aave market DAI", address: import.meta.env.VITE_amDAI },
  { symbol: "Aave market USDC", address: import.meta.env.VITE_amUSDC },
  { symbol: "Aave market USDT", address: import.meta.env.VITE_amUSDT },
  { symbol: "Aave market WBTC", address: import.meta.env.VITE_amWBTC },
  { symbol: "Aave market WETH", address: import.meta.env.VITE_amWETH },
  { symbol: "Aave market WMATIC", address: import.meta.env.VITE_amWMATIC },
];
